2025-02-03T15:08:31.3665647Z ##[group]Run pytest tardis --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m " continuum"
2025-02-03T15:08:31.3666966Z [36;1mpytest tardis --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m " continuum"[0m
2025-02-03T15:08:31.3694841Z shell: /usr/bin/bash -l {0}
2025-02-03T15:08:31.3695082Z env:
2025-02-03T15:08:31.3695258Z   CACHE_NUMBER: 0
2025-02-03T15:08:31.3695882Z   PYTEST_FLAGS: --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append
2025-02-03T15:08:31.3696557Z   CODECOV_TOKEN: 
2025-02-03T15:08:31.3696786Z   MAMBA_ROOT_PREFIX: /home/runner/micromamba
2025-02-03T15:08:31.3697101Z   MAMBA_EXE: /home/runner/micromamba-bin/micromamba
2025-02-03T15:08:31.3697450Z   CONDARC: /home/runner/work/_temp/setup-micromamba/.condarc
2025-02-03T15:08:31.3697788Z ##[endgroup]
2025-02-03T15:08:40.0417492Z ============================= test session starts ==============================
2025-02-03T15:08:40.0418183Z platform linux -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
2025-02-03T15:08:40.0418676Z rootdir: /home/runner/work/tardis/tardis
2025-02-03T15:08:40.0419059Z configfile: pyproject.toml
2025-02-03T15:08:40.0419533Z plugins: anyio-4.4.0, doctestplus-1.2.1, html-4.1.1, metadata-3.1.1, cov-5.0.0
2025-02-03T15:08:40.0420089Z collected 1796 items / 1794 deselected / 2 selected
2025-02-03T15:08:40.0420380Z 
2025-02-03T15:08:41.9885708Z tardis/transport/montecarlo/estimators/tests/test_continuum_property_solver.py E [ 50%]
2025-02-03T15:08:41.9888321Z                                                                          [ 50%]
2025-02-03T15:08:49.2544446Z tardis/transport/montecarlo/tests/test_continuum.py E                    [100%]
2025-02-03T15:08:49.2545516Z 
2025-02-03T15:08:49.2545703Z ==================================== ERRORS ====================================
2025-02-03T15:08:49.2546355Z _________________ ERROR at setup of test_continuum_estimators __________________
2025-02-03T15:08:49.2546800Z 
2025-02-03T15:08:49.2547484Z nlte_atomic_data_fname = PosixPath('/home/runner/work/tardis/tardis/tardis-regression-data/atom_data/nlte_atom_data/TestNLTE_He_Ti.h5')
2025-02-03T15:08:49.2548323Z 
2025-02-03T15:08:49.2548485Z     @pytest.fixture  # (scope="session")
2025-02-03T15:08:49.2548968Z     def nlte_atomic_dataset(nlte_atomic_data_fname):
2025-02-03T15:08:49.2549451Z         """
2025-02-03T15:08:49.2549864Z         Atomic dataset used for NLTE ionization solver tests.
2025-02-03T15:08:49.2550410Z         """
2025-02-03T15:08:49.2550807Z >       nlte_atomic_data = AtomData.from_hdf(nlte_atomic_data_fname)
2025-02-03T15:08:49.2551216Z 
2025-02-03T15:08:49.2551388Z tardis/tests/fixtures/atom_data.py:73: 
2025-02-03T15:08:49.2551894Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2025-02-03T15:08:49.2552389Z tardis/io/atom_data/base.py:192: in from_hdf
2025-02-03T15:08:49.2552854Z     with pd.HDFStore(fname, "r") as store:
2025-02-03T15:08:49.2553556Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/pandas/io/pytables.py:585: in __init__
2025-02-03T15:08:49.2554248Z     self.open(mode=mode, **kwargs)
2025-02-03T15:08:49.2555154Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/pandas/io/pytables.py:745: in open
2025-02-03T15:08:49.2555941Z     self._handle = tables.open_file(self._path, self._mode, **kwargs)
2025-02-03T15:08:49.2556679Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/tables/file.py:294: in open_file
2025-02-03T15:08:49.2557737Z     return File(filename, mode, title, root_uep, filters, **kwargs)
2025-02-03T15:08:49.2558484Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/tables/file.py:744: in __init__
2025-02-03T15:08:49.2559144Z     self._g_new(filename, mode, **params)
2025-02-03T15:08:49.2559582Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2025-02-03T15:08:49.2560161Z 
2025-02-03T15:08:49.2560273Z >   ???
2025-02-03T15:08:49.2560624Z E   tables.exceptions.HDF5ExtError: HDF5 error back trace
2025-02-03T15:08:49.2561073Z E   
2025-02-03T15:08:49.2561332Z E     File "H5F.c", line 836, in H5Fopen
2025-02-03T15:08:49.2561720Z E       unable to synchronously open file
2025-02-03T15:08:49.2562159Z E     File "H5F.c", line 796, in H5F__open_api_common
2025-02-03T15:08:49.2562579Z E       unable to open file
2025-02-03T15:08:49.2562968Z E     File "H5VLcallback.c", line 3863, in H5VL_file_open
2025-02-03T15:08:49.2563392Z E       open failed
2025-02-03T15:08:49.2563752Z E     File "H5VLcallback.c", line 3675, in H5VL__file_open
2025-02-03T15:08:49.2564188Z E       open failed
2025-02-03T15:08:49.2564575Z E     File "H5VLnative_file.c", line 128, in H5VL__native_file_open
2025-02-03T15:08:49.2565236Z E       unable to open file
2025-02-03T15:08:49.2565631Z E     File "H5Fint.c", line 2018, in H5F_open
2025-02-03T15:08:49.2566024Z E       unable to read superblock
2025-02-03T15:08:49.2566405Z E     File "H5Fsuper.c", line 392, in H5F__super_read
2025-02-03T15:08:49.2566826Z E       file signature not found
2025-02-03T15:08:49.2567164Z E   
2025-02-03T15:08:49.2567517Z E   End of HDF5 error back trace
2025-02-03T15:08:49.2567838Z E   
2025-02-03T15:08:49.2568549Z E   Unable to open/create file '/home/runner/work/tardis/tardis/tardis-regression-data/atom_data/nlte_atom_data/TestNLTE_He_Ti.h5'
2025-02-03T15:08:49.2569291Z 
2025-02-03T15:08:49.2569459Z tables/hdf5extension.pyx:512: HDF5ExtError
2025-02-03T15:08:49.2569981Z _________________ ERROR at setup of test_montecarlo_continuum __________________
2025-02-03T15:08:49.2570378Z 
2025-02-03T15:08:49.2571006Z nlte_atomic_data_fname = PosixPath('/home/runner/work/tardis/tardis/tardis-regression-data/atom_data/nlte_atom_data/TestNLTE_He_Ti.h5')
2025-02-03T15:08:49.2571804Z 
2025-02-03T15:08:49.2571964Z     @pytest.fixture  # (scope="session")
2025-02-03T15:08:49.2572425Z     def nlte_atomic_dataset(nlte_atomic_data_fname):
2025-02-03T15:08:49.2572834Z         """
2025-02-03T15:08:49.2573182Z         Atomic dataset used for NLTE ionization solver tests.
2025-02-03T15:08:49.2573641Z         """
2025-02-03T15:08:49.2574001Z >       nlte_atomic_data = AtomData.from_hdf(nlte_atomic_data_fname)
2025-02-03T15:08:49.2574365Z 
2025-02-03T15:08:49.2574520Z tardis/tests/fixtures/atom_data.py:73: 
2025-02-03T15:08:49.2575141Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2025-02-03T15:08:49.2575657Z tardis/io/atom_data/base.py:192: in from_hdf
2025-02-03T15:08:49.2576117Z     with pd.HDFStore(fname, "r") as store:
2025-02-03T15:08:49.2576877Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/pandas/io/pytables.py:585: in __init__
2025-02-03T15:08:49.2577571Z     self.open(mode=mode, **kwargs)
2025-02-03T15:08:49.2578186Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/pandas/io/pytables.py:745: in open
2025-02-03T15:08:49.2578916Z     self._handle = tables.open_file(self._path, self._mode, **kwargs)
2025-02-03T15:08:49.2579657Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/tables/file.py:294: in open_file
2025-02-03T15:08:49.2580396Z     return File(filename, mode, title, root_uep, filters, **kwargs)
2025-02-03T15:08:49.2581126Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/tables/file.py:744: in __init__
2025-02-03T15:08:49.2581769Z     self._g_new(filename, mode, **params)
2025-02-03T15:08:49.2582185Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
2025-02-03T15:08:49.2582499Z 
2025-02-03T15:08:49.2582823Z >   ???
2025-02-03T15:08:49.2583176Z E   tables.exceptions.HDF5ExtError: HDF5 error back trace
2025-02-03T15:08:49.2583621Z E   
2025-02-03T15:08:49.2583916Z E     File "H5F.c", line 836, in H5Fopen
2025-02-03T15:08:49.2584337Z E       unable to synchronously open file
2025-02-03T15:08:49.2585081Z E     File "H5F.c", line 796, in H5F__open_api_common
2025-02-03T15:08:49.2585514Z E       unable to open file
2025-02-03T15:08:49.2586214Z E     File "H5VLcallback.c", line 3863, in H5VL_file_open
2025-02-03T15:08:49.2586664Z E       open failed
2025-02-03T15:08:49.2587029Z E     File "H5VLcallback.c", line 3675, in H5VL__file_open
2025-02-03T15:08:49.2587462Z E       open failed
2025-02-03T15:08:49.2587849Z E     File "H5VLnative_file.c", line 128, in H5VL__native_file_open
2025-02-03T15:08:49.2588317Z E       unable to open file
2025-02-03T15:08:49.2588662Z E     File "H5Fint.c", line 2018, in H5F_open
2025-02-03T15:08:49.2589064Z E       unable to read superblock
2025-02-03T15:08:49.2589475Z E     File "H5Fsuper.c", line 392, in H5F__super_read
2025-02-03T15:08:49.2589930Z E       file signature not found
2025-02-03T15:08:49.2590264Z E   
2025-02-03T15:08:49.2590531Z E   End of HDF5 error back trace
2025-02-03T15:08:49.2590860Z E   
2025-02-03T15:08:49.2591599Z E   Unable to open/create file '/home/runner/work/tardis/tardis/tardis-regression-data/atom_data/nlte_atom_data/TestNLTE_He_Ti.h5'
2025-02-03T15:08:49.2592357Z 
2025-02-03T15:08:49.2592510Z tables/hdf5extension.pyx:512: HDF5ExtError
2025-02-03T15:08:49.2592966Z =============================== warnings summary ===============================
2025-02-03T15:08:49.2593450Z tardis/io/configuration/config_validator.py:6
2025-02-03T15:08:49.2593919Z tardis/io/configuration/config_validator.py:6
2025-02-03T15:08:49.2594840Z   /home/runner/work/tardis/tardis/tardis/io/configuration/config_validator.py:6: DeprecationWarning:
2025-02-03T15:08:49.2595570Z   
2025-02-03T15:08:49.2597514Z   jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
2025-02-03T15:08:49.2599575Z 
2025-02-03T15:08:49.2599948Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22
2025-02-03T15:08:49.2601038Z   /home/runner/micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22: DeprecationWarning:
2025-02-03T15:08:49.2601818Z   
2025-02-03T15:08:49.2602159Z   Jupyter is migrating its paths to use standard platformdirs
2025-02-03T15:08:49.2602728Z   given by the platformdirs library.  To remove this warning and
2025-02-03T15:08:49.2603319Z   see the appropriate new directories, set the environment variable
2025-02-03T15:08:49.2603922Z   `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
2025-02-03T15:08:49.2604531Z   The use of platformdirs will be the default in `jupyter_core` v6
2025-02-03T15:08:49.2605077Z 
2025-02-03T15:08:49.2605396Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
2025-02-03T15:08:49.2605843Z 
2025-02-03T15:08:49.2606092Z ---------- coverage: platform linux, python 3.12.4-final-0 -----------
2025-02-03T15:08:49.2606645Z Coverage HTML written to dir coverage_html_report
2025-02-03T15:08:49.2607119Z Coverage XML written to file coverage.xml
2025-02-03T15:08:49.2607390Z 
2025-02-03T15:08:49.2607573Z =========================== short test summary info ============================
2025-02-03T15:08:49.2617520Z ERROR tardis/transport/montecarlo/estimators/tests/test_continuum_property_solver.py::test_continuum_estimators - tables.exceptions.HDF5ExtError: HDF5 error back trace
2025-02-03T15:08:49.2618582Z 
2025-02-03T15:08:49.2618730Z   File "H5F.c", line 836, in H5Fopen
2025-02-03T15:08:49.2619132Z     unable to synchronously open file
2025-02-03T15:08:49.2619555Z   File "H5F.c", line 796, in H5F__open_api_common
2025-02-03T15:08:49.2620267Z     unable to open file
2025-02-03T15:08:49.2620628Z   File "H5VLcallback.c", line 3863, in H5VL_file_open
2025-02-03T15:08:49.2621038Z     open failed
2025-02-03T15:08:49.2621373Z   File "H5VLcallback.c", line 3675, in H5VL__file_open
2025-02-03T15:08:49.2621775Z     open failed
2025-02-03T15:08:49.2622130Z   File "H5VLnative_file.c", line 128, in H5VL__native_file_open
2025-02-03T15:08:49.2622780Z     unable to open file
2025-02-03T15:08:49.2623110Z   File "H5Fint.c", line 2018, in H5F_open
2025-02-03T15:08:49.2623500Z     unable to read superblock
2025-02-03T15:08:49.2623876Z   File "H5Fsuper.c", line 392, in H5F__super_read
2025-02-03T15:08:49.2624286Z     file signature not found
2025-02-03T15:08:49.2624504Z 
2025-02-03T15:08:49.2624813Z End of HDF5 error back trace
2025-02-03T15:08:49.2625052Z 
2025-02-03T15:08:49.2625642Z Unable to open/create file '/home/runner/work/tardis/tardis/tardis-regression-data/atom_data/nlte_atom_data/TestNLTE_He_Ti.h5'
2025-02-03T15:08:49.2627010Z ERROR tardis/transport/montecarlo/tests/test_continuum.py::test_montecarlo_continuum - tables.exceptions.HDF5ExtError: HDF5 error back trace
2025-02-03T15:08:49.2627776Z 
2025-02-03T15:08:49.2627900Z   File "H5F.c", line 836, in H5Fopen
2025-02-03T15:08:49.2628256Z     unable to synchronously open file
2025-02-03T15:08:49.2628657Z   File "H5F.c", line 796, in H5F__open_api_common
2025-02-03T15:08:49.2629050Z     unable to open file
2025-02-03T15:08:49.2629403Z   File "H5VLcallback.c", line 3863, in H5VL_file_open
2025-02-03T15:08:49.2629806Z     open failed
2025-02-03T15:08:49.2630136Z   File "H5VLcallback.c", line 3675, in H5VL__file_open
2025-02-03T15:08:49.2630549Z     open failed
2025-02-03T15:08:49.2630918Z   File "H5VLnative_file.c", line 128, in H5VL__native_file_open
2025-02-03T15:08:49.2631380Z     unable to open file
2025-02-03T15:08:49.2631692Z   File "H5Fint.c", line 2018, in H5F_open
2025-02-03T15:08:49.2632061Z     unable to read superblock
2025-02-03T15:08:49.2632448Z   File "H5Fsuper.c", line 392, in H5F__super_read
2025-02-03T15:08:49.2632847Z     file signature not found
2025-02-03T15:08:49.2633062Z 
2025-02-03T15:08:49.2633175Z End of HDF5 error back trace
2025-02-03T15:08:49.2633390Z 
2025-02-03T15:08:49.2633984Z Unable to open/create file '/home/runner/work/tardis/tardis/tardis-regression-data/atom_data/nlte_atom_data/TestNLTE_He_Ti.h5'
2025-02-03T15:08:49.2635143Z =============== 1794 deselected, 3 warnings, 2 errors in 10.86s ================
2025-02-03T15:08:50.1437954Z ##[error]Process completed with exit code 1.
