2025-02-28T14:02:00.3915440Z ##[group]Run pytest tardis --tardis-regression-data=/Users/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m "not continuum"
2025-02-28T14:02:00.3916430Z [36;1mpytest tardis --tardis-regression-data=/Users/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m "not continuum"[0m
2025-02-28T14:02:00.3974720Z shell: /bin/bash -l {0}
2025-02-28T14:02:00.3974910Z env:
2025-02-28T14:02:00.3975070Z   CACHE_NUMBER: 0
2025-02-28T14:02:00.3975580Z   PYTEST_FLAGS: --tardis-regression-data=/Users/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append
2025-02-28T14:02:00.3976080Z   CODECOV_TOKEN: 
2025-02-28T14:02:00.3988280Z   MAMBA_ROOT_PREFIX: /Users/runner/micromamba
2025-02-28T14:02:00.3988610Z   MAMBA_EXE: /Users/runner/micromamba-bin/micromamba
2025-02-28T14:02:00.3988950Z   CONDARC: /Users/runner/work/_temp/setup-micromamba/.condarc
2025-02-28T14:02:00.3989320Z ##[endgroup]
2025-02-28T14:02:18.4522610Z ============================= test session starts ==============================
2025-02-28T14:02:18.4524030Z platform darwin -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
2025-02-28T14:02:18.4524540Z rootdir: /Users/runner/work/tardis/tardis
2025-02-28T14:02:18.4525200Z configfile: pyproject.toml
2025-02-28T14:02:18.4525730Z plugins: cov-5.0.0, html-4.1.1, metadata-3.1.1, doctestplus-1.2.1, anyio-4.4.0
2025-02-28T14:02:18.4526350Z collected 1770 items / 1 error / 2 deselected / 1768 selected
2025-02-28T14:02:18.4527170Z 
2025-02-28T14:02:18.4527370Z ==================================== ERRORS ====================================
2025-02-28T14:02:18.4527900Z ___________ ERROR collecting tardis/io/logger/tests/test_logging.py ____________
2025-02-28T14:02:18.4528590Z ImportError while importing test module '/Users/runner/work/tardis/tardis/tardis/io/logger/tests/test_logging.py'.
2025-02-28T14:02:18.4529330Z Hint: make sure your test modules/packages have valid Python names.
2025-02-28T14:02:18.4529930Z Traceback:
2025-02-28T14:02:18.4530380Z ../../../micromamba/envs/tardis/lib/python3.12/importlib/__init__.py:90: in import_module
2025-02-28T14:02:18.4530850Z     return _bootstrap._gcd_import(name[level:], package, level)
2025-02-28T14:02:18.4531330Z tardis/io/logger/tests/test_logging.py:7: in <module>
2025-02-28T14:02:18.4531840Z     from tardis.io.logger.logger import LOGGING_LEVELS
2025-02-28T14:02:18.4532200Z tardis/io/logger/logger.py:5: in <module>
2025-02-28T14:02:18.4533460Z     import panel as pn
2025-02-28T14:02:18.4533770Z E   ModuleNotFoundError: No module named 'panel'
2025-02-28T14:02:18.4534240Z =============================== warnings summary ===============================
2025-02-28T14:02:18.4534580Z tardis/io/configuration/config_validator.py:6
2025-02-28T14:02:18.4535030Z tardis/io/configuration/config_validator.py:6
2025-02-28T14:02:18.4535580Z   /Users/runner/work/tardis/tardis/tardis/io/configuration/config_validator.py:6: DeprecationWarning:
2025-02-28T14:02:18.4536330Z   
2025-02-28T14:02:18.4537650Z   jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
2025-02-28T14:02:18.4539330Z 
2025-02-28T14:02:18.4539650Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22
2025-02-28T14:02:18.4540370Z   /Users/runner/micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22: DeprecationWarning:
2025-02-28T14:02:18.4541030Z   
2025-02-28T14:02:18.4541350Z   Jupyter is migrating its paths to use standard platformdirs
2025-02-28T14:02:18.4541930Z   given by the platformdirs library.  To remove this warning and
2025-02-28T14:02:18.4542380Z   see the appropriate new directories, set the environment variable
2025-02-28T14:02:18.4544470Z   `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
2025-02-28T14:02:18.4544920Z   The use of platformdirs will be the default in `jupyter_core` v6
2025-02-28T14:02:18.4545280Z 
2025-02-28T14:02:18.4545450Z tardis/plasma/properties/__init__.py:17
2025-02-28T14:02:18.4545900Z   /Users/runner/work/tardis/tardis/tardis/plasma/properties/__init__.py:17: DeprecationWarning:
2025-02-28T14:02:18.4546360Z   
2025-02-28T14:02:18.4547130Z   The numpy.linalg.linalg has been made private and renamed to numpy.linalg._linalg. All public functions exported by it are available from numpy.linalg. Please use numpy.linalg.LinAlgError instead.
2025-02-28T14:02:18.4547730Z 
2025-02-28T14:02:18.4547850Z tardis/transport/montecarlo/tests/test_montecarlo.py:557
2025-02-28T14:02:18.4548530Z   /Users/runner/work/tardis/tardis/tardis/transport/montecarlo/tests/test_montecarlo.py:557: PytestUnknownMarkWarning:
2025-02-28T14:02:18.4549110Z   
2025-02-28T14:02:18.4549830Z   Unknown pytest.mark.continuumtest - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
2025-02-28T14:02:18.4550390Z 
2025-02-28T14:02:18.4550510Z tardis/transport/montecarlo/tests/test_montecarlo.py:584
2025-02-28T14:02:18.4551210Z   /Users/runner/work/tardis/tardis/tardis/transport/montecarlo/tests/test_montecarlo.py:584: PytestUnknownMarkWarning:
2025-02-28T14:02:18.4551730Z   
2025-02-28T14:02:18.4552390Z   Unknown pytest.mark.continuumtest - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
2025-02-28T14:02:18.4552940Z 
2025-02-28T14:02:18.4553060Z tardis/transport/montecarlo/tests/test_montecarlo.py:605
2025-02-28T14:02:18.4553780Z   /Users/runner/work/tardis/tardis/tardis/transport/montecarlo/tests/test_montecarlo.py:605: PytestUnknownMarkWarning:
2025-02-28T14:02:18.4554280Z   
2025-02-28T14:02:18.4554860Z   Unknown pytest.mark.continuumtest - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
2025-02-28T14:02:18.4555410Z 
2025-02-28T14:02:18.4555570Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
2025-02-28T14:02:18.4555870Z 
2025-02-28T14:02:18.4556100Z ---------- coverage: platform darwin, python 3.12.4-final-0 ----------
2025-02-28T14:02:18.4556470Z Coverage HTML written to dir coverage_html_report
2025-02-28T14:02:18.4557110Z Coverage XML written to file coverage.xml
2025-02-28T14:02:18.4557260Z 
2025-02-28T14:02:18.4557440Z =========================== short test summary info ============================
2025-02-28T14:02:18.4557970Z ERROR tardis/io/logger/tests/test_logging.py
2025-02-28T14:02:18.4558400Z !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
2025-02-28T14:02:18.4558830Z ================== 2 deselected, 7 warnings, 1 error in 8.10s ==================
2025-02-28T14:02:19.1243390Z ##[error]Process completed with exit code 2.
