2025-02-28T13:54:36.9110094Z ##[group]Run pytest tardis --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m " continuum"
2025-02-28T13:54:36.9111656Z [36;1mpytest tardis --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m " continuum"[0m
2025-02-28T13:54:36.9157484Z shell: /usr/bin/bash -l {0}
2025-02-28T13:54:36.9157727Z env:
2025-02-28T13:54:36.9157909Z   CACHE_NUMBER: 0
2025-02-28T13:54:36.9158535Z   PYTEST_FLAGS: --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append
2025-02-28T13:54:36.9159250Z   CODECOV_TOKEN: 
2025-02-28T13:54:36.9159476Z   MAMBA_ROOT_PREFIX: /home/runner/micromamba
2025-02-28T13:54:36.9159783Z   MAMBA_EXE: /home/runner/micromamba-bin/micromamba
2025-02-28T13:54:36.9160141Z   CONDARC: /home/runner/work/_temp/setup-micromamba/.condarc
2025-02-28T13:54:36.9160502Z ##[endgroup]
2025-02-28T13:54:53.1254153Z ============================= test session starts ==============================
2025-02-28T13:54:53.1255215Z platform linux -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
2025-02-28T13:54:53.1255830Z rootdir: /home/runner/work/tardis/tardis
2025-02-28T13:54:53.1256306Z configfile: pyproject.toml
2025-02-28T13:54:53.1256915Z plugins: metadata-3.1.1, doctestplus-1.2.1, html-4.1.1, cov-5.0.0, anyio-4.4.0
2025-02-28T13:54:53.1257707Z collected 1770 items / 1 error / 1768 deselected / 2 selected
2025-02-28T13:54:53.1258147Z 
2025-02-28T13:54:53.1258339Z ==================================== ERRORS ====================================
2025-02-28T13:54:53.1259016Z ___________ ERROR collecting tardis/io/logger/tests/test_logging.py ____________
2025-02-28T13:54:53.1260109Z ImportError while importing test module '/home/runner/work/tardis/tardis/tardis/io/logger/tests/test_logging.py'.
2025-02-28T13:54:53.1261172Z Hint: make sure your test modules/packages have valid Python names.
2025-02-28T13:54:53.1262139Z Traceback:
2025-02-28T13:54:53.1262656Z ../../../micromamba/envs/tardis/lib/python3.12/importlib/__init__.py:90: in import_module
2025-02-28T13:54:53.1263331Z     return _bootstrap._gcd_import(name[level:], package, level)
2025-02-28T13:54:53.1263854Z tardis/io/logger/tests/test_logging.py:7: in <module>
2025-02-28T13:54:53.1264333Z     from tardis.io.logger.logger import LOGGING_LEVELS
2025-02-28T13:54:53.1264767Z tardis/io/logger/logger.py:5: in <module>
2025-02-28T13:54:53.1265136Z     import panel as pn
2025-02-28T13:54:53.1265482Z E   ModuleNotFoundError: No module named 'panel'
2025-02-28T13:54:53.1265928Z =============================== warnings summary ===============================
2025-02-28T13:54:53.1266375Z tardis/io/configuration/config_validator.py:6
2025-02-28T13:54:53.1266803Z tardis/io/configuration/config_validator.py:6
2025-02-28T13:54:53.1267512Z   /home/runner/work/tardis/tardis/tardis/io/configuration/config_validator.py:6: DeprecationWarning:
2025-02-28T13:54:53.1268188Z   
2025-02-28T13:54:53.1269987Z   jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
2025-02-28T13:54:53.1271990Z 
2025-02-28T13:54:53.1272341Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22
2025-02-28T13:54:53.1273447Z   /home/runner/micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22: DeprecationWarning:
2025-02-28T13:54:53.1274024Z   
2025-02-28T13:54:53.1274299Z   Jupyter is migrating its paths to use standard platformdirs
2025-02-28T13:54:53.1274736Z   given by the platformdirs library.  To remove this warning and
2025-02-28T13:54:53.1275186Z   see the appropriate new directories, set the environment variable
2025-02-28T13:54:53.1275811Z   `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
2025-02-28T13:54:53.1276236Z   The use of platformdirs will be the default in `jupyter_core` v6
2025-02-28T13:54:53.1276501Z 
2025-02-28T13:54:53.1276611Z tardis/plasma/properties/__init__.py:17
2025-02-28T13:54:53.1277118Z   /home/runner/work/tardis/tardis/tardis/plasma/properties/__init__.py:17: DeprecationWarning:
2025-02-28T13:54:53.1277606Z   
2025-02-28T13:54:53.1278338Z   The numpy.linalg.linalg has been made private and renamed to numpy.linalg._linalg. All public functions exported by it are available from numpy.linalg. Please use numpy.linalg.LinAlgError instead.
2025-02-28T13:54:53.1279072Z 
2025-02-28T13:54:53.1279239Z tardis/transport/montecarlo/tests/test_montecarlo.py:557
2025-02-28T13:54:53.1279918Z   /home/runner/work/tardis/tardis/tardis/transport/montecarlo/tests/test_montecarlo.py:557: PytestUnknownMarkWarning:
2025-02-28T13:54:53.1280511Z   
2025-02-28T13:54:53.1281164Z   Unknown pytest.mark.continuumtest - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
2025-02-28T13:54:53.1281921Z 
2025-02-28T13:54:53.1282089Z tardis/transport/montecarlo/tests/test_montecarlo.py:584
2025-02-28T13:54:53.1282763Z   /home/runner/work/tardis/tardis/tardis/transport/montecarlo/tests/test_montecarlo.py:584: PytestUnknownMarkWarning:
2025-02-28T13:54:53.1283294Z   
2025-02-28T13:54:53.1283849Z   Unknown pytest.mark.continuumtest - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
2025-02-28T13:54:53.1284411Z 
2025-02-28T13:54:53.1284558Z tardis/transport/montecarlo/tests/test_montecarlo.py:605
2025-02-28T13:54:53.1285155Z   /home/runner/work/tardis/tardis/tardis/transport/montecarlo/tests/test_montecarlo.py:605: PytestUnknownMarkWarning:
2025-02-28T13:54:53.1285682Z   
2025-02-28T13:54:53.1286240Z   Unknown pytest.mark.continuumtest - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
2025-02-28T13:54:53.1286798Z 
2025-02-28T13:54:53.1286979Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
2025-02-28T13:54:53.1287245Z 
2025-02-28T13:54:53.1287414Z ---------- coverage: platform linux, python 3.12.4-final-0 -----------
2025-02-28T13:54:53.1287776Z Coverage HTML written to dir coverage_html_report
2025-02-28T13:54:53.1288072Z Coverage XML written to file coverage.xml
2025-02-28T13:54:53.1288261Z 
2025-02-28T13:54:53.1288382Z =========================== short test summary info ============================
2025-02-28T13:54:53.1288704Z ERROR tardis/io/logger/tests/test_logging.py
2025-02-28T13:54:53.1289032Z !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
2025-02-28T13:54:53.1289412Z ================ 1768 deselected, 7 warnings, 1 error in 8.99s =================
2025-02-28T13:54:53.7389143Z ##[error]Process completed with exit code 2.
