2025-02-28T13:58:37.9242510Z ##[group]Run pytest tardis --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m "not continuum"
2025-02-28T13:58:37.9243812Z [36;1mpytest tardis --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m "not continuum"[0m
2025-02-28T13:58:37.9289915Z shell: /usr/bin/bash -l {0}
2025-02-28T13:58:37.9290174Z env:
2025-02-28T13:58:37.9290365Z   CACHE_NUMBER: 0
2025-02-28T13:58:37.9291051Z   PYTEST_FLAGS: --tardis-regression-data=/home/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append
2025-02-28T13:58:37.9291786Z   CODECOV_TOKEN: 
2025-02-28T13:58:37.9292029Z   MAMBA_ROOT_PREFIX: /home/runner/micromamba
2025-02-28T13:58:37.9292362Z   MAMBA_EXE: /home/runner/micromamba-bin/micromamba
2025-02-28T13:58:37.9292744Z   CONDARC: /home/runner/work/_temp/setup-micromamba/.condarc
2025-02-28T13:58:37.9293122Z ##[endgroup]
2025-02-28T13:58:53.9548572Z ============================= test session starts ==============================
2025-02-28T13:58:53.9549329Z platform linux -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
2025-02-28T13:58:53.9549909Z rootdir: /home/runner/work/tardis/tardis
2025-02-28T13:58:53.9550831Z configfile: pyproject.toml
2025-02-28T13:58:53.9551398Z plugins: metadata-3.1.1, doctestplus-1.2.1, html-4.1.1, cov-5.0.0, anyio-4.4.0
2025-02-28T13:58:53.9552113Z collected 1770 items / 1 error / 2 deselected / 1768 selected
2025-02-28T13:58:53.9552533Z 
2025-02-28T13:58:53.9552786Z ==================================== ERRORS ====================================
2025-02-28T13:58:53.9553646Z ___________ ERROR collecting tardis/io/logger/tests/test_logging.py ____________
2025-02-28T13:58:53.9554697Z ImportError while importing test module '/home/runner/work/tardis/tardis/tardis/io/logger/tests/test_logging.py'.
2025-02-28T13:58:53.9555675Z Hint: make sure your test modules/packages have valid Python names.
2025-02-28T13:58:53.9556212Z Traceback:
2025-02-28T13:58:53.9556750Z ../../../micromamba/envs/tardis/lib/python3.12/importlib/__init__.py:90: in import_module
2025-02-28T13:58:53.9557514Z     return _bootstrap._gcd_import(name[level:], package, level)
2025-02-28T13:58:53.9558344Z tardis/io/logger/tests/test_logging.py:7: in <module>
2025-02-28T13:58:53.9558897Z     from tardis.io.logger.logger import LOGGING_LEVELS
2025-02-28T13:58:53.9559393Z tardis/io/logger/logger.py:5: in <module>
2025-02-28T13:58:53.9559823Z     import panel as pn
2025-02-28T13:58:53.9560139Z E   ModuleNotFoundError: No module named 'panel'
2025-02-28T13:58:53.9560477Z =============================== warnings summary ===============================
2025-02-28T13:58:53.9560793Z tardis/io/configuration/config_validator.py:6
2025-02-28T13:58:53.9561083Z tardis/io/configuration/config_validator.py:6
2025-02-28T13:58:53.9561565Z   /home/runner/work/tardis/tardis/tardis/io/configuration/config_validator.py:6: DeprecationWarning:
2025-02-28T13:58:53.9562023Z   
2025-02-28T13:58:53.9563258Z   jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
2025-02-28T13:58:53.9564473Z 
2025-02-28T13:58:53.9564715Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22
2025-02-28T13:58:53.9565385Z   /home/runner/micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22: DeprecationWarning:
2025-02-28T13:58:53.9565886Z   
2025-02-28T13:58:53.9566122Z   Jupyter is migrating its paths to use standard platformdirs
2025-02-28T13:58:53.9566512Z   given by the platformdirs library.  To remove this warning and
2025-02-28T13:58:53.9566917Z   see the appropriate new directories, set the environment variable
2025-02-28T13:58:53.9569514Z   `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
2025-02-28T13:58:53.9570120Z   The use of platformdirs will be the default in `jupyter_core` v6
2025-02-28T13:58:53.9570511Z 
2025-02-28T13:58:53.9570686Z tardis/plasma/properties/__init__.py:17
2025-02-28T13:58:53.9571432Z   /home/runner/work/tardis/tardis/tardis/plasma/properties/__init__.py:17: DeprecationWarning:
2025-02-28T13:58:53.9572137Z   
2025-02-28T13:58:53.9573204Z   The numpy.linalg.linalg has been made private and renamed to numpy.linalg._linalg. All public functions exported by it are available from numpy.linalg. Please use numpy.linalg.LinAlgError instead.
2025-02-28T13:58:53.9574241Z 
2025-02-28T13:58:53.9574460Z tardis/transport/montecarlo/tests/test_montecarlo.py:557
2025-02-28T13:58:53.9575084Z   /home/runner/work/tardis/tardis/tardis/transport/montecarlo/tests/test_montecarlo.py:557: PytestUnknownMarkWarning:
2025-02-28T13:58:53.9575640Z   
2025-02-28T13:58:53.9576241Z   Unknown pytest.mark.continuumtest - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
2025-02-28T13:58:53.9576806Z 
2025-02-28T13:58:53.9576958Z tardis/transport/montecarlo/tests/test_montecarlo.py:584
2025-02-28T13:58:53.9577961Z   /home/runner/work/tardis/tardis/tardis/transport/montecarlo/tests/test_montecarlo.py:584: PytestUnknownMarkWarning:
2025-02-28T13:58:53.9578507Z   
2025-02-28T13:58:53.9579068Z   Unknown pytest.mark.continuumtest - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
2025-02-28T13:58:53.9579613Z 
2025-02-28T13:58:53.9579770Z tardis/transport/montecarlo/tests/test_montecarlo.py:605
2025-02-28T13:58:53.9580361Z   /home/runner/work/tardis/tardis/tardis/transport/montecarlo/tests/test_montecarlo.py:605: PytestUnknownMarkWarning:
2025-02-28T13:58:53.9580877Z   
2025-02-28T13:58:53.9581420Z   Unknown pytest.mark.continuumtest - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
2025-02-28T13:58:53.9581961Z 
2025-02-28T13:58:53.9582149Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
2025-02-28T13:58:53.9582434Z 
2025-02-28T13:58:53.9582602Z ---------- coverage: platform linux, python 3.12.4-final-0 -----------
2025-02-28T13:58:53.9582968Z Coverage HTML written to dir coverage_html_report
2025-02-28T13:58:53.9583264Z Coverage XML written to file coverage.xml
2025-02-28T13:58:53.9583451Z 
2025-02-28T13:58:53.9583575Z =========================== short test summary info ============================
2025-02-28T13:58:53.9583889Z ERROR tardis/io/logger/tests/test_logging.py
2025-02-28T13:58:53.9584224Z !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
2025-02-28T13:58:53.9584591Z ================== 2 deselected, 7 warnings, 1 error in 9.00s ==================
2025-02-28T13:58:54.6075050Z ##[error]Process completed with exit code 2.
