2025-01-10T12:23:05.7352090Z ##[group]Run pytest tardis --tardis-regression-data=/Users/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m " continuum"
2025-01-10T12:23:05.7353320Z [36;1mpytest tardis --tardis-regression-data=/Users/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m " continuum"[0m
2025-01-10T12:23:05.7509160Z shell: /bin/bash -l {0}
2025-01-10T12:23:05.7509470Z env:
2025-01-10T12:23:05.7509750Z   CACHE_NUMBER: 0
2025-01-10T12:23:05.7510330Z   PYTEST_FLAGS: --tardis-regression-data=/Users/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append
2025-01-10T12:23:05.7510920Z   CODECOV_TOKEN: 
2025-01-10T12:23:05.7511220Z   MAMBA_ROOT_PREFIX: /Users/runner/micromamba
2025-01-10T12:23:05.7511540Z   MAMBA_EXE: /Users/runner/micromamba-bin/micromamba
2025-01-10T12:23:05.7511990Z   CONDARC: /Users/runner/work/_temp/setup-micromamba/.condarc
2025-01-10T12:23:05.7512490Z ##[endgroup]
2025-01-10T12:23:19.5085110Z 
2025-01-10T12:23:19.5087470Z Iterations:                                                                                0/? [00:00<?, ?it/s]
2025-01-10T12:23:19.5088270Z 
2025-01-10T12:23:19.5090440Z Packets:                                                                                   0/? [00:00<?, ?it/s][AImportError while loading conftest '/Users/runner/work/tardis/tardis/tardis/conftest.py'.
2025-01-10T12:23:19.7297620Z tardis/conftest.py:11: in <module>
2025-01-10T12:23:19.7299600Z     from tardis.simulation import Simulation
2025-01-10T12:23:19.7300960Z tardis/simulation/__init__.py:5: in <module>
2025-01-10T12:23:19.7301390Z     from tardis.simulation.base import Simulation
2025-01-10T12:23:19.7301880Z tardis/simulation/base.py:14: in <module>
2025-01-10T12:23:19.7302310Z     from tardis.io.model.parse_simulation_state import (
2025-01-10T12:23:19.7302960Z tardis/io/model/parse_simulation_state.py:4: in <module>
2025-01-10T12:23:19.7303520Z     from tardis.model import SimulationState
2025-01-10T12:23:19.7303860Z tardis/model/__init__.py:9: in <module>
2025-01-10T12:23:19.7304140Z     from tardis.model.base import SimulationState
2025-01-10T12:23:19.7304500Z tardis/model/base.py:10: in <module>
2025-01-10T12:23:19.7304810Z     from tardis.io.model.parse_composition_configuration import (
2025-01-10T12:23:19.7305210Z tardis/io/model/parse_composition_configuration.py:1: in <module>
2025-01-10T12:23:19.7305690Z     from tardis.io.model.parse_density_configuration import (
2025-01-10T12:23:19.7306060Z tardis/io/model/parse_density_configuration.py:11: in <module>
2025-01-10T12:23:19.7306500Z     from tardis.io.model.parse_geometry_configuration import (
2025-01-10T12:23:19.7306880Z tardis/io/model/parse_geometry_configuration.py:5: in <module>
2025-01-10T12:23:19.7307270Z     from tardis.io.model.readers.base import read_density_file
2025-01-10T12:23:19.7316620Z tardis/io/model/readers/base.py:9: in <module>
2025-01-10T12:23:19.7316990Z     from tardis.io.model.readers.generic_readers import (
2025-01-10T12:23:19.7317470Z tardis/io/model/readers/generic_readers.py:6: in <module>
2025-01-10T12:23:19.7317790Z     from numpy import recfromtxt
2025-01-10T12:23:19.7318420Z E   ImportError: cannot import name 'recfromtxt' from 'numpy' (/Users/runner/micromamba/envs/tardis/lib/python3.12/site-packages/numpy/__init__.py). Did you mean: 'genfromtxt'?
2025-01-10T12:23:20.2291900Z ##[error]Process completed with exit code 4.
