2025-02-28T14:00:25.2510710Z ##[group]Run pytest tardis --tardis-regression-data=/Users/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m " continuum"
2025-02-28T14:00:25.2511730Z [36;1mpytest tardis --tardis-regression-data=/Users/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append -m " continuum"[0m
2025-02-28T14:00:25.2563030Z shell: /bin/bash -l {0}
2025-02-28T14:00:25.2563230Z env:
2025-02-28T14:00:25.2563370Z   CACHE_NUMBER: 0
2025-02-28T14:00:25.2563930Z   PYTEST_FLAGS: --tardis-regression-data=/Users/runner/work/tardis/tardis/tardis-regression-data --cov=tardis --cov-report=xml --cov-report=html --cov-append
2025-02-28T14:00:25.2564430Z   CODECOV_TOKEN: 
2025-02-28T14:00:25.2564600Z   MAMBA_ROOT_PREFIX: /Users/runner/micromamba
2025-02-28T14:00:25.2564860Z   MAMBA_EXE: /Users/runner/micromamba-bin/micromamba
2025-02-28T14:00:25.2565160Z   CONDARC: /Users/runner/work/_temp/setup-micromamba/.condarc
2025-02-28T14:00:25.2565560Z ##[endgroup]
2025-02-28T14:00:43.2512630Z ============================= test session starts ==============================
2025-02-28T14:00:43.2513200Z platform darwin -- Python 3.12.4, pytest-8.2.2, pluggy-1.5.0
2025-02-28T14:00:43.2513470Z rootdir: /Users/runner/work/tardis/tardis
2025-02-28T14:00:43.2513690Z configfile: pyproject.toml
2025-02-28T14:00:43.2513960Z plugins: cov-5.0.0, html-4.1.1, metadata-3.1.1, doctestplus-1.2.1, anyio-4.4.0
2025-02-28T14:00:43.2514340Z collected 1770 items / 1 error / 1768 deselected / 2 selected
2025-02-28T14:00:43.2514530Z 
2025-02-28T14:00:43.2514620Z ==================================== ERRORS ====================================
2025-02-28T14:00:43.2514950Z ___________ ERROR collecting tardis/io/logger/tests/test_logging.py ____________
2025-02-28T14:00:43.2515440Z ImportError while importing test module '/Users/runner/work/tardis/tardis/tardis/io/logger/tests/test_logging.py'.
2025-02-28T14:00:43.2515920Z Hint: make sure your test modules/packages have valid Python names.
2025-02-28T14:00:43.2516360Z Traceback:
2025-02-28T14:00:43.2516640Z ../../../micromamba/envs/tardis/lib/python3.12/importlib/__init__.py:90: in import_module
2025-02-28T14:00:43.2517090Z     return _bootstrap._gcd_import(name[level:], package, level)
2025-02-28T14:00:43.2517440Z tardis/io/logger/tests/test_logging.py:7: in <module>
2025-02-28T14:00:43.2517760Z     from tardis.io.logger.logger import LOGGING_LEVELS
2025-02-28T14:00:43.2518000Z tardis/io/logger/logger.py:5: in <module>
2025-02-28T14:00:43.2518210Z     import panel as pn
2025-02-28T14:00:43.2518390Z E   ModuleNotFoundError: No module named 'panel'
2025-02-28T14:00:43.2518780Z =============================== warnings summary ===============================
2025-02-28T14:00:43.2519030Z tardis/io/configuration/config_validator.py:6
2025-02-28T14:00:43.2519330Z tardis/io/configuration/config_validator.py:6
2025-02-28T14:00:43.2519730Z   /Users/runner/work/tardis/tardis/tardis/io/configuration/config_validator.py:6: DeprecationWarning:
2025-02-28T14:00:43.2520140Z   
2025-02-28T14:00:43.2521170Z   jsonschema.RefResolver is deprecated as of v4.18.0, in favor of the https://github.com/python-jsonschema/referencing library, which provides more compliant referencing behavior as well as more flexible APIs for customization. A future release will remove RefResolver. Please file a feature request (on referencing) if you are missing an API for the kind of customization you need.
2025-02-28T14:00:43.2522270Z 
2025-02-28T14:00:43.2522480Z ../../../micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22
2025-02-28T14:00:43.2523050Z   /Users/runner/micromamba/envs/tardis/lib/python3.12/site-packages/jupyter_client/connect.py:22: DeprecationWarning:
2025-02-28T14:00:43.2523460Z   
2025-02-28T14:00:43.2523710Z   Jupyter is migrating its paths to use standard platformdirs
2025-02-28T14:00:43.2524050Z   given by the platformdirs library.  To remove this warning and
2025-02-28T14:00:43.2524460Z   see the appropriate new directories, set the environment variable
2025-02-28T14:00:43.2525280Z   `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
2025-02-28T14:00:43.2525610Z   The use of platformdirs will be the default in `jupyter_core` v6
2025-02-28T14:00:43.2525800Z 
2025-02-28T14:00:43.2525870Z tardis/plasma/properties/__init__.py:17
2025-02-28T14:00:43.2526280Z   /Users/runner/work/tardis/tardis/tardis/plasma/properties/__init__.py:17: DeprecationWarning:
2025-02-28T14:00:43.2526620Z   
2025-02-28T14:00:43.2527200Z   The numpy.linalg.linalg has been made private and renamed to numpy.linalg._linalg. All public functions exported by it are available from numpy.linalg. Please use numpy.linalg.LinAlgError instead.
2025-02-28T14:00:43.2527690Z 
2025-02-28T14:00:43.2527800Z tardis/transport/montecarlo/tests/test_montecarlo.py:557
2025-02-28T14:00:43.2528290Z   /Users/runner/work/tardis/tardis/tardis/transport/montecarlo/tests/test_montecarlo.py:557: PytestUnknownMarkWarning:
2025-02-28T14:00:43.2528890Z   
2025-02-28T14:00:43.2529340Z   Unknown pytest.mark.continuumtest - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
2025-02-28T14:00:43.2529780Z 
2025-02-28T14:00:43.2529900Z tardis/transport/montecarlo/tests/test_montecarlo.py:584
2025-02-28T14:00:43.2530370Z   /Users/runner/work/tardis/tardis/tardis/transport/montecarlo/tests/test_montecarlo.py:584: PytestUnknownMarkWarning:
2025-02-28T14:00:43.2530820Z   
2025-02-28T14:00:43.2531250Z   Unknown pytest.mark.continuumtest - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
2025-02-28T14:00:43.2531670Z 
2025-02-28T14:00:43.2531790Z tardis/transport/montecarlo/tests/test_montecarlo.py:605
2025-02-28T14:00:43.2532260Z   /Users/runner/work/tardis/tardis/tardis/transport/montecarlo/tests/test_montecarlo.py:605: PytestUnknownMarkWarning:
2025-02-28T14:00:43.2532670Z   
2025-02-28T14:00:43.2533100Z   Unknown pytest.mark.continuumtest - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
2025-02-28T14:00:43.2545570Z 
2025-02-28T14:00:43.2545830Z -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
2025-02-28T14:00:43.2546120Z 
2025-02-28T14:00:43.2546320Z ---------- coverage: platform darwin, python 3.12.4-final-0 ----------
2025-02-28T14:00:43.2546640Z Coverage HTML written to dir coverage_html_report
2025-02-28T14:00:43.2546970Z Coverage XML written to file coverage.xml
2025-02-28T14:00:43.2547180Z 
2025-02-28T14:00:43.2547320Z =========================== short test summary info ============================
2025-02-28T14:00:43.2547590Z ERROR tardis/io/logger/tests/test_logging.py
2025-02-28T14:00:43.2547900Z !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
2025-02-28T14:00:43.2548220Z ================ 1768 deselected, 7 warnings, 1 error in 7.71s =================
2025-02-28T14:00:43.7638400Z ##[error]Process completed with exit code 2.
